### ISSUE TITLE
Category and other filters in media do not work

### ISSUE THREAD

**Issue by kraemer-igroup** [fabarea/vidi#102]
Error: No field type found for "width" in table "sys_file_metadata"
points to https://github.com/fabarea/vidi/blob/master/Classes/Tca/GridService.php#L304

I run into this on two different installations (TYPO3 6.2.6 & 6.2.14) with vidi 1.3.1 an media 3.7.2.

The problems seems width & height in sys_file_metadata not having a configured type.
I temporary "fixed" this with adding the following before line 304:

```php
if($additionalField == 'width' || $additionalField == 'height') {
    continue;
}
```

**Comment by kraemer-igroup** [comment]
These missing field configurations also seem to lead to errors within the core. I reported a related issue here: https://forge.typo3.org/issues/73076

**Comment by fabarea** [comment]
The problem should not appear on a TYPO3 7 LTS. I double checked and fields "width" and "height" are well present in the TCA configuration independently from EXT:filemetadata being activated or not - which adds a bunch of new fields
