### ISSUE TITLE
[BUGFIX] Restore sorting by drag & drop

### ISSUE THREAD

**Issue by fabarea** [fabarea/vidi#104]
After the refactoring of TYPO3 7 LTS, sorting by drag & drop is not that far to be restored but currently fail because of missing JS library. I suspect we need some jQuery UI lib.

Here is the code that need to be investigated. https://github.com/fabarea/vidi/blob/master/Resources/Public/JavaScript/DataTables/dataTables.rowReordering.js#L202

To easily test, enabled in the EM of Vidi, data type "tt_content" (new option). After reloading the BE, the Content module offers a manual sorting. Commenting out the code in dataTables.rowReordering.js#L202 will lead to an error.

@jmverges can help here?

**Comment by jmverges** [comment]
hey @fabarea 
After install the extension with composer I'm getting this when I click on any BE Module from vide like Page Content:
![image](https://cloud.githubusercontent.com/assets/2902073/11483363/49538840-97a8-11e5-8fb3-29059481036a.png)

any clue?

**Comment by fabarea** [comment]
I think class auto-loading is still miss-configured in the composer.json of the extension according to [this post](http://insight.helhum.io/post/130876393595/how-to-configure-class-loading-for-extensions-in). Does it change something for you when adding in composer.json in key `autoload`:

```
"classmap": ["Classes"]
```

**Comment by fabarea** [comment]
Please `composer update` of `dev-master`. It should be fixed by https://github.com/fabarea/vidi/commit/993d953f293ac4265941005bd1284b36a6cc1317. If the problem persists, also give a little hand by `composer dump-autoload`.
