### ISSUE TITLE
Getting Call to undefined method when using with media

### ISSUE THREAD

**Issue by Gregor-Agnes** [fabarea/vidi#123]
Installed versions from TER:
vidi 2.03
media 4.0.2
TYPO3 7.6.4

Getting **Call to undefined method Fab\Vidi\Persistence\Matcher::getInCriteria() in /var/www/sieben-sechs-vier/site/typo3conf/ext/vidi/Classes/Service/ClipboardService.php on line 51**

when changing to the (Media)-filelist

**Comment by fabarea** [comment]
Hotfix released has been made on the TER 2.0.4
