### ISSUE TITLE
several issues with update vidi >0.9.1 and media >3.5.3

### ISSUE THREAD

**Issue by gizmo21** [fabarea/vidi#130]
As media needs a security update I thought it would be good to update also vidi, but i have several problems with updating to versions >0.9.1 on Typo3 6.2.<newest>(tried several times now).
i don't need vidi for anything else then media (3.7.5).

* first if i update vidi to any version >0.9.1 (up to 1.3.1)  (and media still 3.5.3.) right after update there is a 
* Fatal error: Class 'TYPO3\CMS\Vidi\Facet\StandardFacet' not found in /www/typo3conf/ext/media/Configuration/TCA/Overrides/sys_file.php on line 39
or
* Fatal error: Class 'Fab\Vidi\Facet\StandardFacet' not found in /www/typo3conf/ext/media/Configuration/TCA/Overrides/sys_file.php on line 43
or
* Fatal error: Class 'TYPO3\CMS\Vidi\Facet\StandardFacet' not found in /var/www/typo3conf/ext/media/Configuration/TCA/Overrides/sys_file.php on line 39 

>>blocking the whole back- AND frontend<<

* I then have to disable vidi AND media in  /typo3conf/PackageStates.php by setting 'state' => 'inactive' and delete typo3temp/Cache via OS-filemanager

* then i can reinstall old versions vidi=0.9.1 and media=3.5.3 and everything is working again. Tried this with serveral extension- and typo3-version updates now - always the same --> but now there is this security fix in media and i REALLY HAVE to update this time.

**Comment by gizmo21** [comment]
One of the errors 
Fatal error: Class 'TYPO3\CMS\Backend\Template\Components\Buttons\LinkButton' not found in /www/--------/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4469


seem to be that after updating manually to vidi 1.3.1 and then updating media to 3.7.5 it automagically installs vidi 2.x which is not compatible with typo3 6.2 it seems (or at least with media 3.7.5 which itself is the latest for 6.2).

**Comment by fabarea** [comment]
Sorry for not replying earlier. It looks the version number of Vidi is missing in Media < 4
https://github.com/fabarea/media/blob/3.7.5/ext_emconf.php

**Comment by fabarea** [comment]
Just released EXT:media 3.7.6 with TYPO3 6.2 Vidi compatibility as dependency. Should avoid all these issues.... https://github.com/fabarea/media/tree/3.7.6
