### ISSUE TITLE
vidi seems to work only in live workspace

### ISSUE THREAD

**Issue by ZwergNase** [fabarea/vidi#14]
Hello everyone!

I am trying to get EXT:media and thus EXT:vidi running on my Typo3 6.2.11 (php 5.6.6) installation. Everything seems fin as long as I am in the default LIVE workspace. As soon as I switch workspace to something different than life, I get the following error in the MEDIA module:

`#1: PHP Catchable Fatal Error: Argument 2 passed to TYPO3\CMS\Vidi\Domain\Model\Content::__construct() must be of the type array, boolean given, called in .../typo3_src-6.2.11/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4437 and defined in .../typo3conf/ext/vidi/Classes/Domain/Model/Content.php line 47`

Any help would be very welcome!

Cheers,
Oliver

**Comment by fabarea** [comment]
Can you confirm whether the error is Media specific or not: do you get the same error for the Vidi FE User module? 

There already were some fixes addressing issues with workspaces but FAL is quite special in the matter.

**Comment by ZwergNase** [comment]
Yes, both user modules fail the same ways. 
Just to be sure, i'll set up a clean 6.2 system later and add only media and vidi. I'll let you know about any findings.

Oliver

**Comment by BoBaH83** [comment]
found the code, where the array isn't an array anymore:
htdocs/typo3conf/ext/vidi/Classes/Persistence/Storage/VidiDbBackend.php:1090

where it says:
// @todo It looks for me this code will never be used! "_ORIG_uid" is something from extbase. Adjust me or remove me in 0.4 + 2 version!
$pageRepository->versionOL($tableName, $row, TRUE);

modifying to 
$pageRepository->versionOL($tableName, $row, TRUE, TRUE);

seems to solve this issue, but I'm not sure if this is an issue for use in other cases.
