### ISSUE TITLE
Browse Subfolders option not visible

### ISSUE THREAD

**Issue by christophlehmann** [fabarea/vidi#149]
When i open a content element and add try to add an image i don't see the checkbox "browse sub-folders. I click on the settings (top right) and close the settings (x top left). Then i see the checkbox.

It seems like a bug for me.

**Comment by fabarea** [comment]
Rather a EXT:media question but you're right. You get instead a dropdown menu listing all the storage. Notice images will all be displayed within this list so "browse sub-folders" is implicit. It is very difficult to include the iframe containing the folder tree in the popup without heavy refactoring. Hoping situation will be easier with 8.x.

![image](https://cloud.githubusercontent.com/assets/620730/19516197/30578c54-95fb-11e6-8cc1-c7c262d7e771.png)
