### ISSUE TITLE
Issues with media 3.7.6 and vidi 1.3.0+ in TYPO 6.2.25

### ISSUE THREAD

**Issue by jblum66** [fabarea/vidi#152]
Hi,

In TYPO3 6.2.25 with PHP 5.4.36, I have issues when upgrading media and vidi.
The last version of media for TYPO3 6.2 is v3.7.6. It needs vidi 1.3.0 or 1.3.1.

When vidi 1.3.x is installed then activated, if I activate media 3.7.6, I get this error:
`Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /home/wwwroot/anah/www/typo3conf/ext/vidi/Classes/Grid/ColumnRendererAbstract.php on line 180`

If I check vidi again, it has automaticaly upgraded to 2.2.0!

**Comment by fabarea** [comment]
Vidi and EXT:media are not supported anymore on TYPO3 6.2. If you provide patches though, I can merge them on the 6.2 branch.
