### ISSUE TITLE
Change cache configuration to only override the minimum

### ISSUE THREAD

**Issue by sypets** [fabarea/vidi#159]
If the cache configuration is changed as recommended in the core api (https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/CachingFramework/Configuration/Index.html#cache-configurations), it would be possible to set a different backend in LocalConfiguration.php / AddidtionalConfiguration.php. Currently the backend always defaults to the DatabaseBackend. The options get overridden entirely.

What I mean is change this:

```
$TYPO3_CONF_VARS['SYS']['caching']['cacheConfigurations']['vidi'] = array(
    'frontend' => 'TYPO3\CMS\Core\Cache\Frontend\VariableFrontend',
    'options' => array(
        'defaultLifetime' => 2592000, // => 1 month
    ),
    'groups' => array('all', 'vidi')
);

```

to something like this:

```
$TYPO3_CONF_VARS['SYS']['caching']['cacheConfigurations']['vidi']['frontend'] = \TYPO3\CMS\Core\Cache\Frontend\VariableFrontend::class;
$TYPO3_CONF_VARS['SYS']['caching']['cacheConfigurations']['vidi']['groups'] = array('all', 'vidi');
$TYPO3_CONF_VARS['SYS']['caching']['cacheConfigurations']['vidi']['options']['defaultLifetime'] = 2592000;
```

**Comment by fabarea** [comment]
Perhaps you are already preparing it... but in case not, could you provide with a PR and I will merge that?

**Comment by sypets** [comment]
right. PR is created. Hope everything is ok. I made the same minor changes as in rss_display. 

Thanks for providing these extensions and happy coding!
