### ISSUE TITLE
Breaks with TYPO3 8.7.7

### ISSUE THREAD

**Issue by fnagel** [fabarea/vidi#167]
`Call to undefined method Fab\Vidi\Grid\CheckBoxRenderer::__set_state() `

Might be related to the TCA caching changes.

**Comment by kassor** [comment]
I confirm this issue

**Comment by cundd** [comment]
As mentioned by @fnagel it is likely caused by https://review.typo3.org/54062 and/or https://review.typo3.org/54154

**Comment by fnagel** [comment]
Actually I'm a little upset how such a change could be included in a patch level update.

**Comment by fabarea** [comment]
Will have a look what we could figure out.

**Comment by fabarea** [comment]
TER version is on its way.

**Comment by opi99** [comment]
While trying the patch and trying latest master of vidi, I found that this issue still persists.

**Comment by fabarea** [comment]
It shouldn't. Could you make sure the cache was properly and deeply flushed.

Even with a `rm -rf typo3temp/Cache`

**Comment by zzzooorrrx** [comment]
For me it's working in Typo3 8.7.8 with 2.6.0

**Comment by opi99** [comment]
I did `rm -rf typo3temp/var` ... will try again with 2.6.0 from TER

**Comment by opi99** [comment]
*hmpf* Ok, all fine, got it ... need to patch my own TCA which was calling CheckBoxRenderer same way. :-)

All fine, thanks.

**Comment by V35CH** [comment]
Error after update Typo3 8.7.9 with vidi 2.6.0 from TER
