### ISSUE TITLE
Error after install on Typo3 8.7.8

### ISSUE THREAD

**Issue by bucheggerOnline** [fabarea/vidi#168]
Hi.
The ext is not working on Typo3 8.7.8, after installing the system crushes down.
Error: Call to undefined method Fab\Vidi\Grid\CheckBoxRenderer::__set_state()

**Comment by fabarea** [comment]
It looks the TER version was not up to date. I just went to the new extensions.typo3.org and uploaded the extension again. Please, install version 2.6.0 (should be visible soon) and do a deep flush of the cache `rm -rf typo3temp/Cache`. It should do the trick.
