### ISSUE TITLE
Columns visibilty not working properly

### ISSUE THREAD

**Issue by sahdev-nitsan** [fabarea/vidi#169]
Hello

Some columns are showing when checkbox is not checked and not showing when checkbox is checked:
https://prnt.sc/h3uyxh , https://prnt.sc/h3uzr2

if you don't find this issue then follow this step:
1) when we select any check box field from vidi extension module for show 
2) then we only click other modules from backend 
3) then we back to vidi module again and we can see thisissue.

I have added this extension in three to four project, same issue for all  .

please help asap!!!

Regards

**Comment by fabarea** [comment]
You could:

- empty your localStorage in the browser
- flush table `cf_vidi` and `tx_vidi_preference` in the database.

It should settle the case.
