### ISSUE TITLE
DataTables warning

### ISSUE THREAD

**Issue by Hobokens** [fabarea/vidi#179]
Hi,
after installing vidi 2.7.  with TYPO3 8.7.18 l get always the following error when opening a folder with images or documents

"DataTables warning: table id=content-list - Requested unknown parameter 'metadata.fe_groups' for row 0, column 12. For more information about this error, please see http://datatables.net/tn/4"

I can ignore the warning and see the folder content then.
My browser is firefox.

Regards
Hobokens

**Comment by fabarea** [comment]
Was released as bug fix in v2.7.1
