### ISSUE TITLE
Extension-settings cannot be opened/edited in ExtensionManager

### ISSUE THREAD

**Issue by christianbaer** [fabarea/vidi#191]
IN TYPO3 9.5.8 (composer mode) I cannot open the configuration of the EXT:vidi in ExtenstionManager. The edit-button is simply missing.

Workaround: Change the values (like data_types) in LocalConfiguration.php

**Comment by fabarea** [comment]
Can you provide with a PR? That would be great.

**Comment by fabarea** [comment]
![image](https://user-images.githubusercontent.com/620730/63245501-a1e06f00-c260-11e9-962c-374def2748ea.png)

I can not reproduce the error
