### ISSUE TITLE
pages_language_overlay

### ISSUE THREAD

**Issue by GurneyHallack** [fabarea/vidi#2]
Hi, 

If I use List2, with Alternative Page Language, I have the follow error in js :
"Oups! Something went wrong with the Ajax request... Investigate the problem in the Network Monitor. "
With display error on, that 
TYPO3\CMS\Vidi\Persistence\Storage\VidiDbBackend::getRowsFromResult(mysqli_result)
doesn't working.

I think it's because pages_language_overlay is not extbased.

Perhaps it would be usefull to add a condition on the table, and use this command if it's pages_language_overlay :
$GLOBALS['TYPO3_DB']->exec_SELECTgetRows('*', 'pages_language_overlay', 'pid=' . (int)$this->id . BackendUtility::deleteClause('pages_language_overlay') . BackendUtility::versioningPlaceholderClause('pages_language_overlay'), '', '', '', 'sys_language_uid');

**Comment by jmverges** [comment]
I'm also interested in be able to work with pages_language_overlay. @GurneyHallack where do you say that we should write that code?

**Comment by fabarea** [comment]
> I think it's because pages_language_overlay is not extbased.
Yes, the Typo3DbBackend from Extbase has been adapted and pages overlay does not work well their. There is nothing I can do unless heavily digging into VidiDbBackend. I would support the patch but I can't do it right now.
