### ISSUE TITLE
Take care of TCA maxitems default value in function FieldService->hasOne()

### ISSUE THREAD

**Issue by cgerold** [fabarea/vidi#59]
As the default value for *maxitems* in TCA configuration is 1 there might be some need for an additional check in FieldService->hasOne(). Because if you do not explicitly set the parameter in your TCA configuration the function does not return true and the request fails with:

> Could not determine type of relation.

I would suggest to check if the parameter *maxitems* is not available (so its value is 1 by default) or is explicit set to 1. The affected line should be in vidi/Classes/Tca/FieldService.php:602
```
return $this->hasRelation() && ($configuration['maxitems'] == 1 || !isset($configuration['maxitems']))
```

TYPO3 TCA Documentation: https://docs.typo3.org/typo3cms/TCAReference/Reference/Columns/Select/Index.html#maxitems

**Comment by fabarea** [comment]
A shame we don't have Unit Tests here... I started something but never completed. Anyway, thanks for your feedback.

**Comment by fabarea** [comment]
Mmm... I had to reverted the patch (well,... I pushed force the patch with a comment). I now have an error in EXT:media (master). Can you have a look by you?

Here is the exact message:

```
 Fatal error: Uncaught exception 'TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\SqlErrorException' with message 
'Unknown column 'sys_category.items.sys_file_metadata' in 'on clause': SELECT DISTINCT 
sys_category.* FROM sys_category LEFT JOIN sys_file_metadata ON 
sys_category.items.sys_file_metadata=sys_file_metadata.uid AND sys_file_metadata.t3ver_state<=0 
AND sys_file_metadata.pid<>-1 AND (sys_file_metadata.sys_language_uid IN (0,-1)) WHERE 
sys_file_metadata.uid = '499' AND sys_category.t3ver_state<=0 AND sys_category.pid<>-1 AND 
sys_category.deleted=0 AND (sys_category.sys_language_uid IN (0,-1))' in 
typo3conf/ext/vidi/Classes/Persistence/Storage/VidiDbBackend.php on line 1209
```

**Comment by cgerold** [comment]
Yes you're right. The problem is the TCA type *group*. The documentation says there is also the default value 1 for *maxitems*. But if there is a MM relation it wont be respected. Therefore we could check as following:

```
	public function hasOne() {
		$configuration = $this->getConfiguration();

		if (isset($configuration['MM'])) {
			return false;
		}

		return $this->hasRelation() && ($configuration['maxitems'] == 1 || !isset($configuration['maxitems']));
	}
```

**Comment by fabarea** [comment]
We have the correction version, now.
