### ISSUE TITLE
Exception is thrown if a facet is configured for a field of a datatype (table name) other than  ModuleLoader::getDataType

### ISSUE THREAD

**Issue by mostwanted1976** [fabarea/vidi#6]
#1385554481: Does the field really exist? No TCA entry found for field "title"

This only happens in FacetSuggestionService::getSuggestions() if [1] the field is not configured as text area and [2] the number of suggestions is lower or equal the configured limit.

Example: additional facet for sys_file_metadata.title for EXT:media

**Comment by mostwanted1976** [comment]
I will send a pull request!

**Comment by mostwanted1976** [comment]
I just sent a pull request: https://github.com/fabarea/vidi/pull/7

**Comment by fabarea** [comment]
Was merged.
