### ISSUE TITLE
TYPO3 Fatal Error: Trying to flush table "cf_vidi" with "Clear All Cache"

### ISSUE THREAD

**Issue by rabe69** [fabarea/vidi#66]
This is not the right way to register a cache table clearing under 6.2:
```
$TYPO3_CONF_VARS['SC_OPTIONS']['t3lib/class.t3lib_tcemain.php']['clearAllCache_additionalTables']['cf_vidi'] = 'cf_vidi';
```
1. This hook is marked as deprecated
2. The table name does not ends with "cache"

The result of the second point is the error message in the subject, if you try to delete all caches using the TYPO3 CLI.

**Comment by fabarea** [comment]
Do you have a patch / code snippet to give a direction?

**Comment by mischka** [comment]
You should define which kind of Cache you use an add the group "all" I think.

```
$TYPO3_CONF_VARS['SYS']['caching']['cacheConfigurations']['vidi'] = array(
        'frontend' => 'TYPO3\CMS\Core\Cache\Frontend\VariableFrontend',
        'options' => array(
            'defaultLifetime' => 804600
        ),
        'groups' => array('all', 'vidi')
    );
```
http://docs.typo3.org/typo3cms/CoreApiReference/CachingFramework/Developer/Index.html
