### ISSUE TITLE
[BUG] All language in media (initializeLocalizedStructure)

### ISSUE THREAD

**Issue by Simperfit** [fabarea/vidi#68]
Hello,

I don't know if this is a known bug or not, bug we have some problem using media + vidi with a localized TYPO3

We have more than 20 languages and we cannot limit the language with the be_users

**Comment by fabarea** [comment]
Will be part of 1.0.1. Release on his way.

**Comment by Simperfit** [comment]
Thank you

**Comment by Simperfit** [comment]
Why does i have this error ?

 Fatal error: Call to a member function findByDataTypeForCurrentBackendUser() on a non-object in /usr/src/typo3conf/ext/vidi/Classes/Controller/Backend/ContentController.php on line 63

Is there something to configure ?

Using both an admin with no localized & backend user with localize

**Comment by fabarea** [comment]
I suspect a caching issues -> flush system cache. Alternatively truncate all tables starting with cf_* in your database + rm -rf typo3temp/Cache
